a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
maximum = max(a, b, c)
minimum = min(a, b, c)
print("Maximum number is:", maximum)
print("Minimum number is:", minimum)
